[features]
seeds = false
skip-lint = false
[programs.devnet]
bones_poker_contract = "A6gEoFvGyNPyYjYs7kQLibAsn3H8wD5f4rVDvBjTVace"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/solana/bone-poker-contract/bones-poker-contract/BP-deploy-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
